name: e2e-tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  e2e-tests:
    name: e2e-tests
    permissions: write-all
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e-tests
      cancel-in-progress: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Create test.json
        run: |
          cat << EOF > config/test.json
          {
            "testChains": {
              "84532": {
                "rpcUrl": "https://base-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY }}"
              },
              "10": {
                "rpcUrl": "https://opt-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY }}"
              },
              "1": {
                "rpcUrl": "https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY }}"
              }
            },
            "includeInTests": [84532, 10, 1]
          }
          EOF

      - name: Run the tests
        run: bun run test
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
